---
- name: Download and uncompress Yara source
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  unarchive:
    src: https://github.com/VirusTotal/yara/archive/v{{ yara_ver }}.tar.gz
    dest: "{{ build_dir }}"
    remote_src: true

- name: Bootstrap Yara
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: ./bootstrap.sh
  args:
    chdir: "{{ build_dir }}/yara-{{ yara_ver }}"

- name: Configure Yara
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: "./configure --enable-cuckoo --enable-magic"
  args:
    chdir: "{{ build_dir }}/yara-{{ yara_ver }}"

- name: Compile Yara
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: make
  args:
    chdir: "{{ build_dir }}/yara-{{ yara_ver }}"

- name: Install Yara
  become: true
  become_method: sudo
  shell: make install
  args:
    chdir: "{{ build_dir }}/yara-{{ yara_ver }}"
